# Save as ..codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
  
exclude_paths:
- tests/**/*
- spec/**/*
- "**/vendor/**/*"
- public/**
- db/schema.rb
