development:
  adapter: postgresql
  encoding: unicode
  database: watchiot
  pool: 5
  username: gorums
  password: androidebkl3600

test:
  adapter: postgresql
  encoding: unicode
  database: watchiot_test
  pool: 5
  username: gorums
  password: androidebkl3600